CE-539: fix ammo not showing up when losing weapons in natla's mines
stohrendorf/CroftEngine pull request #236
Opened 2022-07-07 02:14 UTC by serishema

CE-539

2022-07-07 05:09 UTC, stohrendorf requested changes
Didn't test this yet, but overall looks very good.

2022-07-07 05:09 UTC, stohrendorf commented on src/menu/compassmenustate.cpp
> +    if(inv.count(ammo.weaponType) == 0 && ammo.shots && ammo.hits == 0 && ammo.hitsTotal == 0 && ammo.misses == 0
```suggestion
    if(inv.count(ammo.weaponType) == 0 && ammo.shots != 0 && ammo.hits == 0 && ammo.hitsTotal == 0 && ammo.misses == 0
```

Forgot to write an explicit comparison there when I wrote this.

2022-07-07 20:32 UTC, serishema commented on src/engine/objects/laraobject.cpp
> +void LaraObject::shootBullet(const WeaponType weaponType,
This algorithm is commonly called "hitscan" by gamers. 
so `hitscanSingleRound` comes to mind.

2022-07-08 03:50 UTC, stohrendorf commented on src/engine/objects/laraobject.cpp
> +void LaraObject::shootBullet(const WeaponType weaponType,
That's perfect.

2022-07-08 03:53 UTC, stohrendorf requested changes
Just one last thing.

2022-07-08 03:53 UTC, stohrendorf commented on src/engine/inventory.cpp
> +  auto addWeapon = [this](Ammo& ammo)
```suggestion
  auto addWeapon = [this](const Ammo& ammo)
```

2022-07-08 04:37 UTC, stohrendorf approved these changes
Good. Didn't test it yet, but if you're confident it works, you can squash, rebase and merge.

2022-07-08 07:22 UTC, merged